### ISSUE TITLE
Can't send log to Pastebin.

### ISSUE THREAD

**Issue by CesarHerreraG** [NeoTheThird/Logviewer#12]
![screenshot20190122_195551586](https://user-images.githubusercontent.com/29006270/51558516-ebf6a300-1e7f-11e9-872b-4d4a5d48960a.png)

**Comment by advocatux** [comment]
To anyone having this issue, there's a workaround: go to Settings in Logviewer, and change the Pastebin username by default (that "Ubuntu Touch User"). Any random one-word username should be enough.

Other users have confirmed that it works that way (See for example https://forums.ubports.com/post/17828)

**Comment by Danfro** [comment]
For me this works. But after entering a username, I had to press return to sort of confirm the input. Otherwise it would be lost.
