### ISSUE TITLE
Pastebin empty

### ISSUE THREAD

**Issue by MK1973** [NeoTheThird/Logviewer#2]
The app announce Pastebin is successful but it is empty.

**Comment by mymike00** [comment]
I confirm this bug
![immagine](https://user-images.githubusercontent.com/28359593/36936111-e801a558-1f00-11e8-8620-36a62349c9c6.png)

**Comment by NeoTheThird** [comment]
This was caused by some changes introduced by paste.ubuntu.com. Fixed in 1.1.
