### ISSUE TITLE
[xenial] Paste to pastebin doesn't work, err 502

### ISSUE THREAD

**Issue by zubozrout** [NeoTheThird/Logviewer#8]
Hi,
I've tried to upload a log to pastebin but it returned an arror an in the app's log I can see the site returned a 502 error, Bad Gateway.

Is it just a xenial issue? (though I would expect not)

Thank you very much for looking into this :)

**Comment by advocatux** [comment]
I can confirm this bug on BQ E4.5 (krillin) running Ubuntu 16.04 (r95).

**Comment by cibersheep** [comment]
Try changing the user in the settings. Also very long log I think sometimes gives this error also
